name: ollama_app
description: "تطبيق Flutter احترافي ومتقدم للتفاعل مع Ollama API"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Design - Compatible versions
  cupertino_icons: ^1.0.6
  dynamic_color: ^1.6.8
  flutter_animate: ^4.2.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  cached_network_image: ^3.2.3
  flutter_markdown: ^0.6.18
  markdown: ^7.1.1

  # State Management
  provider: ^6.0.5

  # Network & API - Stable versions
  dio: ^5.3.2
  http: ^0.13.6
  connectivity_plus: ^4.0.2

  # Database & Storage - Compatible versions
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Media & Files - Stable versions
  image_picker: ^1.0.4
  file_picker: ^5.5.0
  image: ^4.1.3
  path: ^1.8.3

  # Audio & Speech
  flutter_tts: ^3.8.5

  # Utilities - Compatible versions
  uuid: ^3.0.7
  intl: ^0.20.2
  url_launcher: ^6.1.14
  share_plus: ^7.2.1
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  permission_handler: ^11.0.1

  # Charts & Analytics
  fl_chart: ^0.64.0

  # Security & Encryption
  crypto: ^3.0.3
  encrypt: ^5.0.3
  local_auth: ^2.1.6

  # PDF & Export
  pdf: ^3.10.6
  printing: ^5.11.0

  # Notifications
  flutter_local_notifications: ^15.1.1

  # JSON Serialization
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
    - assets/fonts/

  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Cairo-Light.ttf
  #         weight: 300
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Light.ttf
  #         weight: 300
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
