name: ollama_app
description: "تطبيق Flutter احترافي ومتقدم للتفاعل مع Ollama API"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  material_color_utilities: ^0.8.0
  dynamic_color: ^1.6.8
  flutter_animate: ^4.2.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  cached_network_image: ^3.2.3
  flutter_markdown: ^0.6.18
  markdown: ^7.1.1

  # State Management
  provider: ^6.1.2

  # Network & API
  dio: ^5.4.3+1
  http: ^1.2.1
  connectivity_plus: ^6.0.3

  # Database & Storage
  sqflite: ^2.3.3+1
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Media & Files
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  image: ^4.2.0
  path: ^1.9.0

  # Audio & Speech (simplified)
  flutter_tts: ^4.0.2

  # Utilities
  uuid: ^4.4.0
  intl: ^0.20.2
  url_launcher: ^6.2.6
  share_plus: ^11.0.0
  device_info_plus: ^11.5.0
  package_info_plus: ^8.0.0
  permission_handler: ^12.0.0+1

  # Charts & Analytics
  fl_chart: ^1.0.0

  # Security & Encryption
  crypto: ^3.0.3
  encrypt: ^5.0.3
  local_auth: ^2.1.8

  # PDF & Export
  pdf: ^3.10.8
  printing: ^5.12.0

  # Notifications
  flutter_local_notifications: ^19.3.0

  # JSON Serialization
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
    - assets/fonts/

  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Cairo-Light.ttf
  #         weight: 300
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Light.ttf
  #         weight: 300
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
