# أبسط حل لمشكلة Dart SDK
# انسخ هذا إذا لم يعمل الحل الأول

name: Simple APK Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
    
    - run: flutter config --no-analytics
    - run: flutter pub get
    - run: flutter build apk --release
    
    - uses: actions/upload-artifact@v3
      with:
        name: apk
        path: build/app/outputs/flutter-apk/app-release.apk
